#:kivy 1.9.0


<DrpDwnList>:
    #orientation: 'lr-tb'
    #padding: 0
    spacing: 0
    #width: root.width
    #height: 15
    size: 1, 0.5
    Label:
        font_size: 10
        text:  str(root.label_text)
    TextInput:
        font_size: 12
        text: str(root.label_text)


<MyFace>:
    orientation: 'lr-bt'
    padding: 10
    spacing: 25
    size_hint: 1, 0.1

    Button:
        on_press: root.some_action()
        pos: self.pos
        size: self.size



